# Generated by Django 4.2.22 on 2025-06-06 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicelog',
            options={'ordering': ['-date', 'student_name'], 'verbose_name': '練習記錄', 'verbose_name_plural': '練習記錄'},
        ),
        migrations.AddField(
            model_name='practicelog',
            name='focus',
            field=models.CharField(blank=True, help_text='本次練習的重點項目', max_length=200, verbose_name='練習重點'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='notes',
            field=models.TextField(blank=True, help_text='練習過程中的觀察和心得', verbose_name='練習筆記'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='date',
            field=models.DateField(db_index=True, help_text='練習的日期', verbose_name='練習日期'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='minutes',
            field=models.PositiveIntegerField(help_text='練習時間長度', validators=[django.core.validators.MinValueValidator(1)], verbose_name='練習時間（分鐘）'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='piece',
            field=models.CharField(help_text='練習的樂曲名稱', max_length=200, verbose_name='練習曲目'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='練習效果自評（1-5分）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='練習評分'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='student_name',
            field=models.CharField(db_index=True, help_text='練習學生的姓名', max_length=100, verbose_name='學生姓名'),
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['student_name', 'date'], name='practice_lo_student_72f252_idx'),
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['date'], name='practice_lo_date_403669_idx'),
        ),
    ]
