# Generated by Django 4.2.22 on 2025-06-09 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0002_alter_practicelog_options_practicelog_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicelog',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='練習的日期', verbose_name='練習日期'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='focus',
            field=models.CharField(choices=[('technique', '技巧練習'), ('expression', '表現力'), ('rhythm', '節奏'), ('sight_reading', '視奏'), ('memorization', '記譜'), ('ensemble', '重奏'), ('other', '其他')], default='technique', help_text='本次練習的重點項目', max_length=20, verbose_name='練習重點'),
        ),
    ]
