# Generated by Django 4.2.22 on 2025-06-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0003_alter_practicelog_date_alter_practicelog_focus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['student_name', 'piece'], name='practice_lo_student_0cbd3f_idx'),
        ),
    ]
