# Generated by Django 4.2.22 on 2025-06-11 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0006_teacherfeedback_delete_practicetask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicelog',
            name='self_rating_expression',
        ),
        migrations.RemoveField(
            model_name='practicelog',
            name='self_rating_pitch',
        ),
        migrations.RemoveField(
            model_name='practicelog',
            name='self_rating_rhythm',
        ),
        migrations.AddField(
            model_name='practicelog',
            name='ensemble_listening',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='與其他聲部的聆聽配合（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='聆聽配合'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='ensemble_timing',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='與其他樂器的時間同步（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='時間同步'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='expression_dynamics',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='音量強弱控制（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='力度變化'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='expression_emotion',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='音樂情感傳達（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='情感表達'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='expression_phrasing',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='音樂線條與樂句表現（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='樂句處理'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='memorization_confidence',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='背譜演奏的自信程度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='記譜信心'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='memorization_stability',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='背譜演奏的穩定程度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='記憶穩定度'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='rhythm_pattern_accuracy',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='複雜節奏型的準確演奏（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='節奏型準確度'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='rhythm_tempo_stability',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='節拍速度保持穩定（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='速度穩定度'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='sight_reading_accuracy',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='音符、節奏讀譜準確度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='視奏準確度'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='sight_reading_fluency',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='第一次看譜演奏的流暢程度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='視奏流暢度'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='technique_bow_control',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='運弓技巧控制度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='運弓控制'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='technique_finger_position',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='左手按弦位置準確度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='按弦準確度'),
        ),
        migrations.AddField(
            model_name='practicelog',
            name='technique_intonation',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='音準準確度（1-5星）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='音準'),
        ),
    ]
