# Generated by Django 4.2.22 on 2025-06-11 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0007_remove_practicelog_self_rating_expression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '學生'), ('teacher', '教師'), ('admin', '系統管理員'), ('parent', '家長')], default='student', help_text='選擇用戶在系統中的角色', max_length=20, verbose_name='用戶角色')),
                ('chinese_name', models.CharField(blank=True, help_text='用戶的中文姓名', max_length=50, verbose_name='中文姓名')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='電話號碼格式：+999999999，最多15位數字', regex='^\\+?1?\\d{9,15}$')], verbose_name='聯絡電話')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('avatar', models.ImageField(blank=True, help_text='上傳個人頭像圖片', null=True, upload_to='avatars/%Y/%m/', verbose_name='頭像')),
                ('bio', models.TextField(blank=True, help_text='簡短描述自己的音樂背景或學習目標', max_length=500, verbose_name='個人簡介')),
                ('skill_level', models.CharField(choices=[('beginner', '初學者'), ('intermediate', '中級'), ('advanced', '高級'), ('professional', '專業級')], default='beginner', help_text='當前的小提琴演奏程度', max_length=20, verbose_name='小提琴程度')),
                ('learning_start_date', models.DateField(blank=True, help_text='開始學習小提琴的日期', null=True, verbose_name='開始學習日期')),
                ('learning_goals', models.TextField(blank=True, help_text='描述學習小提琴的目標和期望', max_length=1000, verbose_name='學習目標')),
                ('favorite_composers', models.CharField(blank=True, help_text='例如：巴哈、莫札特、貝多芬', max_length=200, verbose_name='喜愛的作曲家')),
                ('profile_public', models.BooleanField(default=False, help_text='是否允許其他用戶查看個人資料', verbose_name='公開個人資料')),
                ('practice_logs_public', models.BooleanField(default=False, help_text='是否允許其他用戶查看練習記錄', verbose_name='公開練習記錄')),
                ('email_notifications', models.BooleanField(default=True, help_text='接收系統通知和提醒', verbose_name='電子郵件通知')),
                ('practice_reminders', models.BooleanField(default=True, help_text='接收練習提醒通知', verbose_name='練習提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶資料',
                'verbose_name_plural': '用戶資料',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='practice_lo_role_7d0367_idx'), models.Index(fields=['chinese_name'], name='practice_lo_chinese_f00f16_idx'), models.Index(fields=['skill_level'], name='practice_lo_skill_l_bb53a1_idx'), models.Index(fields=['created_at'], name='practice_lo_created_c3ca8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登入時間')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP位址')),
                ('user_agent', models.TextField(blank=True, verbose_name='瀏覽器資訊')),
                ('login_successful', models.BooleanField(default=True, help_text='登入是否成功', verbose_name='登入成功')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='登出時間')),
                ('session_duration', models.DurationField(blank=True, null=True, verbose_name='會話時長')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '登入記錄',
                'verbose_name_plural': '登入記錄',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='practice_lo_user_id_2b7e8e_idx'), models.Index(fields=['ip_address'], name='practice_lo_ip_addr_c60ad2_idx'), models.Index(fields=['login_time'], name='practice_lo_login_t_d7458c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentTeacherRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='師生關係建立的時間', verbose_name='開始時間')),
                ('end_date', models.DateField(blank=True, help_text='師生關係結束的時間（如果適用）', null=True, verbose_name='結束時間')),
                ('is_active', models.BooleanField(default=True, help_text='師生關係是否仍然有效', verbose_name='關係狀態')),
                ('notes', models.TextField(blank=True, help_text='關於這個師生關係的特殊說明', max_length=500, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relations', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to=settings.AUTH_USER_MODEL, verbose_name='教師')),
            ],
            options={
                'verbose_name': '師生關係',
                'verbose_name_plural': '師生關係',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='practice_lo_student_fe5f82_idx'), models.Index(fields=['teacher', 'is_active'], name='practice_lo_teacher_462af7_idx'), models.Index(fields=['start_date'], name='practice_lo_start_d_ea45ad_idx')],
                'unique_together': {('student', 'teacher', 'start_date')},
            },
        ),
    ]
