# Generated by Django 4.2.22 on 2025-06-11 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0008_userprofile_userloginlog_studentteacherrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerecording',
            name='privacy_level',
            field=models.CharField(choices=[('public', '公開'), ('teacher_only', '僅教師可見'), ('private', '私人')], default='private', help_text='控制誰可以觀看此影片', max_length=20, verbose_name='隱私設定'),
        ),
        migrations.AddField(
            model_name='practicerecording',
            name='recording_date',
            field=models.DateField(blank=True, help_text='實際錄製這個影片的日期', null=True, verbose_name='錄音日期'),
        ),
        migrations.AlterField(
            model_name='practicerecording',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, help_text='記錄這是第幾週的練習錄音', null=True, verbose_name='第幾週錄音'),
        ),
        migrations.CreateModel(
            name='TeacherNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_video', '新影片上傳'), ('video_comment', '影片評論'), ('student_feedback', '學生回饋'), ('system', '系統通知')], max_length=20, verbose_name='通知類型')),
                ('title', models.CharField(max_length=200, verbose_name='通知標題')),
                ('message', models.TextField(verbose_name='通知內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='閱讀時間')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_logs.practicerecording', verbose_name='相關影片')),
                ('student', models.ForeignKey(help_text='觸發通知的學生', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_as_student', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
                ('teacher', models.ForeignKey(help_text='接收通知的教師', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教師')),
            ],
            options={
                'verbose_name': '教師通知',
                'verbose_name_plural': '教師通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'is_read'], name='practice_lo_teacher_a56599_idx'), models.Index(fields=['notification_type'], name='practice_lo_notific_d87ea3_idx'), models.Index(fields=['created_at'], name='practice_lo_created_b3d701_idx')],
            },
        ),
    ]
