# Generated by Django 4.2.22 on 2025-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0009_practicerecording_privacy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_background',
            field=models.TextField(blank=True, help_text='教師的音樂教育背景和資歷', max_length=500, verbose_name='教育背景'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='教師的專業領域，例如：古典音樂、流行音樂、室內樂等', max_length=200, verbose_name='專業領域'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_philosophy',
            field=models.TextField(blank=True, help_text='教師的教學方法和理念', max_length=1000, verbose_name='教學理念'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='教學經驗的年數', null=True, verbose_name='教學經驗年數'),
        ),
    ]
