# Generated by Django 4.2.22 on 2025-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0011_questioncategory_resourcecategory_studentquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_group',
            field=models.CharField(blank=True, default='ungrouped', help_text='教師為學生設定的分組', max_length=50, verbose_name='學生分組'),
        ),
    ]
