# Generated by Django 4.2.22 on 2025-06-11 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0012_userprofile_student_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'display_order', '-helpful_count'], 'verbose_name': '常見問題', 'verbose_name_plural': '常見問題'},
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='practice_lo_categor_00836f_idx',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.AddField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faqs', to=settings.AUTH_USER_MODEL, verbose_name='創建者'),
        ),
        migrations.AddField(
            model_name='faq',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='顯示順序'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='已發布'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='color',
            field=models.CharField(default='#2c5f3d', help_text='HEX顏色代碼', max_length=7, verbose_name='顏色代碼'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='practice_logs.questioncategory', verbose_name='問題分類'),
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='有幫助次數'),
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='is_public',
            field=models.BooleanField(default=False, help_text='是否允許其他學生查看此回答', verbose_name='公開回答'),
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='unhelpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='沒幫助次數'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-question-circle', help_text='FontAwesome圖標類別名稱', max_length=50, verbose_name='圖標類別'),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='status',
            field=models.CharField(choices=[('pending', '待回答'), ('answered', '已回答'), ('closed', '已關閉')], default='pending', max_length=20, verbose_name='狀態'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_published'], name='practice_lo_categor_007c99_idx'),
        ),
    ]
