# Generated by Django 4.2.22 on 2025-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0013_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='practicelog',
            new_name='idx_stud_date',
            old_name='practice_lo_student_72f252_idx',
        ),
        migrations.RenameIndex(
            model_name='practicelog',
            new_name='idx_date',
            old_name='practice_lo_date_403669_idx',
        ),
        migrations.RenameIndex(
            model_name='practicelog',
            new_name='idx_stud_piece',
            old_name='practice_lo_student_0cbd3f_idx',
        ),
        migrations.RenameIndex(
            model_name='practicelog',
            new_name='idx_mood',
            old_name='practice_lo_mood_99145e_idx',
        ),
        migrations.RenameIndex(
            model_name='practicelog',
            new_name='idx_created',
            old_name='practice_lo_created_d8f090_idx',
        ),
        migrations.RenameIndex(
            model_name='practicelog',
            new_name='idx_stud_created',
            old_name='practice_lo_student_9a35fe_idx',
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['focus', 'date'], name='idx_focus_date'),
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['rating', 'date'], name='idx_rating_date'),
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['-date', 'student_name'], name='idx_date_desc_stud'),
        ),
        migrations.AddConstraint(
            model_name='practicelog',
            constraint=models.CheckConstraint(check=models.Q(('minutes__gte', 1), ('minutes__lte', 600)), name='valid_practice_minutes'),
        ),
        migrations.AddConstraint(
            model_name='practicelog',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating_range'),
        ),
    ]
